### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Hannav** [funktionaalinen-graafinen-kieli/backlogs#103]
[Suunnitelma](https://docs.google.com/presentation/d/1qmQ3TawMZj208WseLQdrsC7WH0Aj38y7c8iJsumZBL4/edit#slide=id.g6e0be74b66_0_0)

Tiketöidyt:
- [ ] useita hahmoja, jotka käyttäytyvät samalla tavalla (esim. pelin kenttä jossa vihollisia: kaikki samanlaisia, liikkuvat satunnaisiin suuntiin, kaikilla voisi olla sama funktio, joka liikuttaa niitä) #127
- [ ] pelinäkymän suurentaminen halutessa (palikkanäkymä pienentyy) (~~#144~~), #171 

Tiketöimättömät:
- [ ] näkyy/ei näy-nappi tai välähdys pelinäkymässä sen hahmon ympärillä joka on valittu, jotta samannäköisistä hahmoista erottaa, mitä tarkoitetaan
- [ ] debug- & xml-napit piiloon lasten versiossa
- [ ] testataan väkästen muotojen intuitiivisuutta
- [ ] pistelaskuri-kuva
- [ ] muut grafiikat
- [ ] mahdollisuus lisätä omia hahmokuvia
- [ ] mahdollisuus lisätä omia taustoja
- [ ] nappien selkeys: label vai kirjoitetaanko nappeihin niiden toiminta?
- [ ] hahmovalikkoon säädöt koolle, suunnalle ja sijainnille koordinaatistossa
- [ ] hiiren koordinaattien lopullinen paikka
- [ ] error message nollalla jakamisesta
- [ ] Pelialue aina näkyvissä, ei vain kun peli on käynnistetty

Alhaisen prioriteetin:
- [ ] vertikaaliset palikat (osoittautunut hankalaksi)
- [ ] roskis aktivoituu kun palikat reuna koskettaa sitä (käden ei tarvitse olla roskiksen kohdalla)
- [ ] lokaalituki
- [ ] pistelaskuriin lokaalituki
- [ ] "funktiokirjasto"

Jo tehdyt:

- [x] logo 
- [x] Entity-tabit: scratchissa voi katsoa per hahmo, voisiko jaotella jotenkin, esim. kytketty eventti, jotta lapset näkevät selkeästi hahmonsa tapahtumiin liittyvän koodin #92
- [x] pikkukuvat x- ja y-akseleille #164
- [x] fullscreen-nappi (maximize, minimize)
- [x] (~~roskikset tai~~) x:t hahmojen ja taustojen poistolle
- [x] kursori on eri vikassa napissa
- [x] saako kaksoispisteet pois, tarvitaanko niitä?
- [x] valitun kohteen ympäröimä sininen pois
- [x] pyöreämmät kulmat ulkoasussa
- [x] hiiren koordinaattien kertominen #131
- [x] nimeämisen selkeys #146 
- [x] väkästen pitää muuttua riippuen tyypistä #106
- [x] play/pause- nappula, stop- nappula, muut valmiissa tarvittavat nappulat #120
- [x] Kun entityn x fn tai y fn :ssä ei ole kiinni funktiota, näytä default "hae <this>" funktio #115
- [x] default kuva selkeäksi defaultiksi #116
- [x] Selkeät default nimet / idt #117
- [x] koodin muutosten näkyminen pelinäkymässä reaaliajassa #114 (vähintään uudelleenkäynnistämällä) 
- [x] palikkanäkymän sisällön suurentaminen ja pienentäminen

**Comment by xylix** [comment]
CSS Grid muunnos palautetta:
- [] Tiedostovalitsin ylempänä kuin muut napit
- [] onko tapaa ottaa label väripalikat pois päältä
- Peli edelleen vakiokokoinen

Voisiko pelientityjen kanssa siirtyä prosenttipohjaiseen liikkumiseen?
