### ISSUE TITLE
Käyttöohje opetuksen ohjaajalle / järjestäjälle

### ISSUE THREAD

**Issue by xylix** [funktionaalinen-graafinen-kieli/backlogs#110]
- [ ] valitaan millä teknisellä ratkaisulla renderöidään / servetään ohjeet

- [ ] Miten saada lapset alkuun ohjelmoinnin kanssa
- [ ] Ohjelmien teko-ohjeita
- [ ] ohjeet yleisistä ongelmatilanteista käyttäjien ohjelmoidessa

Linkkejä:
https://www.cs.helsinki.fi/group/linkki/materiaali/kirjastopaja/Kerailypeli.html
https://www.cs.helsinki.fi/group/linkki/materiaali/lapsiohjeet/kerailypeli/kerailypeli.pdf
https://www.cs.helsinki.fi/group/linkki/materiaali/kirjastopaja/kerailypeli.html
https://www.cs.helsinki.fi/group/linkki/materiaali/kirjastopaja/

Tarvitaan ohje lapsille IV periodin koekäyttöön (ks. myös #105)

- [x] kirjallinen ohje: Kilpikonnapeliohje.txt

Ohjeen sisältö:
* peli-idea (jokin mistä lapset tykkää)
* tavoite pelille (ei tarvitse olla monimutkainen, ehkä jokin vaikeustasovaihtoehto)
* pisteiden kerääminen
