### ISSUE TITLE
entity-tabs jatkokehitettävää

### ISSUE THREAD

**Issue by xylix** [funktionaalinen-graafinen-kieli/backlogs#177]
- [ ] tyyppi SetCharacterMap sopivampaan tiedostoon kuin app.tsx
- [ ] vertical scrollbar jos paljon entityjä?
- [ ] loput character selector css css tiedostoon inlinen sijaan
- [ ] kysy käyttäjältä uuden entityn nimi
- [ ] Monimutkaisella koodilla (koodi joka tarvitsee muuttuja-arvoja) määritellyt hahmokuvat eivät näy character selectorissa
- [ ] bugi: pitää uudelleenvalita joku hahmo hahmolistasta että muutokset päivittyvät peliin / muihin tietorakenteisiin
