### ISSUE TITLE
Tekninen velka

### ISSUE THREAD

**Issue by xylix** [funktionaalinen-graafinen-kieli/backlogs#181]
luettavuus / muokattavuus
- [ ] Blockeihin mukaan tyyppimetadataa ettei tarvitse hardkoodaa useaan paikkaan
- [ ] palikoiden luomiseen paremmat omat apufunktiot, tällä hetkellä registration ja generator .tsx ovat aika copypastea #50 
- [ ] sonar koodinhajujen korjailu https://sonarcloud.io/dashboard?id=funktionaalinen-graafinen-kieli_funkly
- [ ] initital_xml pois piilosta BlocklyEditor/BlocklyReact:ista

Blockly-kustomisaatiot:
Parannettuja apufunktioita omien palikoiden määrittelemiseen
  - [x] dropdowneille
  - [ ] palikka-json luontiin
  - [ ] järkevä generator.tsx ja registration.tsx erottelu. Yhden palikan määritelmä mieluiten yhtenä könttänä koodia eikä pilkottuna kahteen tiedostoon
  - [ ] Muita parannuksia palikoiden kirjottamisen helpottamiseen

suorituskyky:
- [ ] Selvitetään tarpeet (käyttäjien ohjelmointitietokoneet) ja nykyinen suorituskyky esim. linkin malliprojektin kaltaisilla toteutuksilla
- [ ] Ennaltaladataan kuvat kun tabi aukeaa, ennen kuin peli avataan

pelimoottorin toiminnalliset outoudet:
- [ ] Ajastimen parmepi synccaaminen oikeisiin millisekunteihin
- [ ] Käytetään oikeaa pelimoottoria? Vähentäisi maintainattavaa koodia mutta vaikeuttaisi muokattavuutta https://www.npmjs.com/package/react-game-engine 

eval / tyyppivirheet:
- [ ] Parempi (virheviesteissä ja turvallisuudessa) json validointi kuin `parse catch` tai eval
- [ ] Rikkovien string-inputtien jne purifiointi
