### ISSUE TITLE
Implementoimattomat ominaisuudet

### ISSUE THREAD

**Issue by Hannav** [funktionaalinen-graafinen-kieli/backlogs#182]
- [ ] Koodin muutosten näkyminen pelinäkymässä reaaliajassa (Säilytetään tila mutta korvataan funktiot kun blockly-palikkakasa muuttuu)
- [ ] Projektien / varsinkin kuva-assettien tallentaminen (omien kuvien uploadaus tuki, assettien tallentaminen xml tiedostoon muun projektin mukaan, tietokantaan / driveen tjsp tallentaminen?)
- [ ] String construction block
- [ ] Timer block
- [ ] Touchscreen input
- [ ] Kielen määrittely / vaihtamis ominaisuudet, vähintään suomi implementoituna
- [ ] Pelialueen keskipiste 0,0:ksi koordinaatistossa
- [ ] Entityjen vetäminen aloitussijainnista toiseen
- [ ] play napin painamisen jälkeen input focus pelialueeseen
- [ ] Entityille Z-akseli / kyky määritellä kumpi on päällä kun entityt overlappaavat
- [ ] Scratch tyylinen törmääminen kahden kuvan overlappaavia pikseleitä vertaamalla
