### ISSUE TITLE
Bugit

### ISSUE THREAD

**Issue by xylix** [funktionaalinen-graafinen-kieli/backlogs#190]
- [ ] entityissä svg kuvat eivät veny oikein
  - [some relevant info](https://stackoverflow.com/questions/39056537/why-don-t-my-svg-images-scale-using-the-css-width-property/39062462#39062462)
Possible solution is to make sure all svg images have `width` and `height` set to `"100%"` 
- [ ] Entity tabeja vaihtaessa guard blockit unohtaa ovatko viimeisiä
- [ ] Entityjä lisätessä viitteet entityyn näkyvät alkuun ? / undefinedinä
